### ISSUE TITLE
Don't use Yueliang, please

### ISSUE THREAD

**Issue by Reinitialized** [Open-SB/OpenSB#3]
# Issue
Yueliang is an unoptimized Lua 5.1 compiler, and with newer solutions now available, should not be used.

# Solution
Using an HTTP backend, interface with Luau to compile source to bytecode, then run returned results through Fiu for client execution. This can be accomplished two ways:
- Write the HTTP server and compiler logic using Lune (NOT RECOMMENDED, Lune http.serve is currently unstable without some weird hacks)
- Write the HTTP server using Bun/NodeJS which interfaces with Lune to compile (RECOMMENDED)

**Comment by ewd3v** [comment]
The current [compile.luau](https://github.com/Open-SB/OpenSB/blob/main/modules/shared/compile.luau) that uses Yueliang is actually not in use anywhere in the codebase as of right now. The plan is to use it for LocalScripts.
At the time of adding the file I was planning on using Yueliang with FiOne to compile and interpret LocalScripts, but I've changed my mind (because my goal is to have near 100% compatibility with normal Roblox script behavior).

As of right now I'm going to use Fiu to interpret scripts, but I'm not 100% sure how I want to compile them. I'm not planning on writing an opensource backend for OpenSB, so I'd rather have all the compiling done inside of Roblox (something like LuauCeption is too big, but it might still work).

**Comment by ewd3v** [comment]
If LuauCeption doesn't work for OpenSB I might write an opensource Bun backend (under OpenSB) that has an endpoint to compile Luau.

**Comment by techs-sus** [comment]
Here's the repo for luau-compile. https://github.com/Open-SB/luau-compile

**Comment by Reinitialized** [comment]
Although LuaCeption is indeed an option, I intentionally left it out as from my personal experience:
- it was over 400k lines and hard to navigate due to strain it puts on the IDE
- its not very performant

For the most part, barring expected random periods of high latency, implementing a Bun backend to handle this task would be the most performant.

**Comment by ewd3v** [comment]
Yeah I don't want to use LuauCeption either, we opted to making a [Rust backend instead](https://github.com/Open-SB/luau-compile) (was going to use Bun but asked tech if he could make one with Rust instead).

**Comment by techs-sus** [comment]
Also, eventually we can containerize the Rust backend. Using Bun would rely on hacky techniques (bun.$) or hard to write FFI bindings. In Rust however, mlua has already implemented the bindings, which means we can use higher level abstractions and we can benefit from their active maintainers.

**Comment by ewd3v** [comment]
I'll be closing this as we plan to support Luau on locals with [Fiu](https://github.com/rce-incorporated/Fiu) and [luau-compile](https://github.com/Open-SB/luau-compile).

**Comment by ewd3v** [comment]
[Localscripts now have Luau support](https://github.com/Open-SB/OpenSB/commit/e44a9dd4d45b2a44708ba15c86b3637e7eeaeb2c).
